### ISSUE TITLE
Integration. Starting 20th Dec

### ISSUE THREAD

**Issue by CeliaDiaz17** [MariaBlancoGonzalez/ISOFT2-2021-A02#28]
Today we've started the integration of our project.

**Comment by CeliaDiaz17** [comment]
We've decided to create a module with all the JFrames, and another one with all the dependencies which will be in a superior level than the modules that we already had with the code belonging to each one of the use cases.

**Comment by CeliaDiaz17** [comment]
To make easier the unification/merge we have had a meeting in which we decided how each module had to be implemented in Maven(classes belonging to that module, how should be the pom, etc) so we have uploaded in each iteration a last file with these "failures" solved.

**Comment by MarioMar15** [comment]
Since yesterday (21/12/2020) we have been trying to merge the iterations, but as we had a problem with the pom files, saying that there are confilicts between them, we have not finished it yet.
