### ISSUE TITLE
Starting Design part of Iteration 1  [08 Nov 2020]

### ISSUE THREAD

**Issue by CeliaDiaz17** [MariaBlancoGonzalez/ISOFT2-2021-A02#3]
Work to be implemented in this phase:
Class diagram, states diagram and sequence diagram.

Deadline: Hope to finish the Design phase of the iteration 1 on 15 Nov 2020

**Comment by CeliaDiaz17** [comment]
**Class diagram:**

- Started: 8th Nov.  
- Finished: 11th Nov.
- Time expended: 3 hours

**Sequence Diagram:**

- Started: Wednesday 11th Nov
- Finished: Friday 13th Nov
- Time expended: 6 hours


**Note:** Hours are an aproximation because as we kept on working we were realizing we had some things to change.

**Comment by CeliaDiaz17** [comment]
Changing the presentation field of the iteration 1 by adding a Jframe class to implement the login.

**Comment by ghost** [comment]
End the design part

**Comment by CeliaDiaz17** [comment]
**Fixing some errors:**

- Ending sequence diagram taking into account the changing of state of a table when this is reserved.
- Fixing little parts of the class diagram.
- Making sure that all the methods where written the same way in the class diagram and in the second diagram so it wouldn't create problems later on


**Participants:**

-  Maria Blanco 
-  Celia Díaz

**Comment by CeliaDiaz17** [comment]
Reopened the design of the implementation 1 because when we found out some better way to do some parts of the design. We "redesigned" a couple of classes and fixed some errors from the sequence diagrams.

Work done by Maria Blanco Gonzalez-Mohino and Celia Díaz Fernández.
