### ISSUE TITLE
Starting Design part of Iteration 2 [08 Nov 2020]

### ISSUE THREAD

**Issue by AdrianRuiz6** [MariaBlancoGonzalez/ISOFT2-2021-A02#5]
Work to be implemented in this phase:
Class diagram and sequence diagram.

Deadline: hope to finish the design phase of the iteration 2 on 15 Nov 2020

**Comment by MariaJesusDuenasRecuero** [comment]
Developing class diagram on 11th Nov 2020

**Comment by MariaJesusDuenasRecuero** [comment]
**Finish class diagram [12 Nov 2020]**
Starts on 8th November 2020 and working 1:30 hours
Developing 11th  November 2020 working  1 hour
Ends 12th  November  2020  1 hours 

Total: 3:30 hours

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours

Total: 4:30 hours
We planned this part to be finished in 6 hours and we have finished it in 8 hours.

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections 14th November 2020 1:05 hour

Total: 1 hour and 5 minute
We planned this part to be finished in 6 hours and we have finished it in 9 hours with 5 minutes.

**Comment by AdrianRuiz6** [comment]
We have reopenned the design part of this iteration due to some problems solved after talking with Ismael.

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour

Total: 3 hours
We planned this part to be finished in 6 hours and we have finished it in 12 hours with 5 minutes.

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours

Total: 2 hours
We planned this part to be finished in 6 hours and we have finished it in 14 hours with 5 minutes.

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours
Corrections4 30th November 2020 1 hour

Total: 1 hours
We planned this part to be finished in 6 hours and we have finished it in 15 hours with 5 minutes.

**Comment by AdrianRuiz6** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours
Corrections4 30th November 2020 1 hour
Corrections5 3rd December 2020 5 minutes

Total: 5 minutes
We planned this part to be finished in 6 hours and we have finished it in 15 hours with 15 minutes.

**Comment by MariaJesusDuenasRecuero** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours
Corrections4 30th November 2020 1 hour
Corrections5 3rd December 2020 5 minutes
Corrections6 4th December 2020 10 minutes

Total: 10 minutes
We planned this part to be finished in 6 hours and we have finished it in 15 hours with 25 minutes.

**Comment by MariaJesusDuenasRecuero** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours
Corrections4 30th November 2020 1 hour
Corrections5 3rd December 2020 5 minutes
Corrections6 4th December 2020 10 minutes
Corrections7 5th December 2020 10 minutes

Total: 10 minutes
We planned this part to be finished in 6 hours and we have finished it in 15 hours with 35 minutes.

**Comment by MariaJesusDuenasRecuero** [comment]
Finish sequence diagram [13 Nov 2020]
Starts on 12th November 2020 and working 1:30 hours
Developing 12th November 2020 working 1 hour
Ends 13th November 2020 2 hours
Corrections1 14th November 2020 1:05 hour
Corrections2 23th November 2020 3 hour
Corrections3 29th November 2020 2 hours
Corrections4 30th November 2020 1 hour
Corrections5 3rd December 2020 5 minutes
Corrections6 4th December 2020 10 minutes
Corrections7 5th December 2020 10 minutes
Corrections8 6th December 2020 10 minutes

Total: 10 minutes
We planned this part to be finished in 6 hours and we have finished it in 15 hours with 45 minutes.
