### ISSUE TITLE
Implementation iteration 1 [15th November 2020]

### ISSUE THREAD

**Issue by AdrianRuiz6** [MariaBlancoGonzalez/ISOFT2-2021-A02#6]
Mario and I are going to make the implementation part of the iteration 1.

**Comment by AdrianRuiz6** [comment]
We are delaying this phase one week because we had some doubts about it and we want to solve them before starting.

**Comment by MarioMar15** [comment]
Today both Adrian and I finally have continued the implementation.

**Comment by MarioMar15** [comment]
Finish implementation [9 Dec 2020]
Starts on December 4th 2020 and working 4 hours
Ends December 9th 2020 working an ammount of 3 hours

Total: 7 hours
We planned this part to be finished in 4 hours and we have finished it in 7 hours.

**Comment by MarioMar15** [comment]
Updated the implementation after a meeting with Ismael.

**Comment by MarioMar15** [comment]
Finish implementation [9 Dec 2020]
Starts on December 4th 2020 and working 4 hours
Ends December 9th 2020 working an ammount of 3 hours
Corrections made on December 12th with an ammount 2 hours worked

Total: 9 hours 
We planned this part to be finished in 4 hours and we have finished it in 9 hours.
